### ISSUE TITLE
Missing "EventSource.js" in production build profile

### ISSUE THREAD

**Issue by phuonghuynh** [veluxa/sciterjs-react#2]
I got missing file error when building using "prod" profile, is there any missing code in this repository? @veluxa 

Anyway, thanks for the great code, I learnt from this so much.

**Comment by veluxa** [comment]
Thank you, it has been fixed, please pull the latest code and try again, this error is the previous processing sciterjs hot update left behind forgot to delete.

**Comment by phuonghuynh** [comment]
Closed due to it fixed
